server:
  port: 8989
  servlet:
    context-path: /server

#这个可以被TestUserDetailsService来代替 在那里密码可以从数据库中查
#security:
#  user:
#    password: 123456

#可以被TestAuthorizationServerConfig替代
#security:
#  oauth2:
#    client:
#      clientId: self
#      clientSecret: selfSecret
##     这句必须加 不然会报错At least one redirect_uri must be registered with the client
#      registered-redirect-uri: http://example.com


